<?php

namespace landing\controllers;

use models\Products;
use models\PropertyValue24;
use Yii;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use yii\web\NotFoundHttpException;

/**
 * Site controller
 */
class CatalogController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function beforeAction($action)
    {
        try {
            return parent::beforeAction($action);
        } catch (BadRequestHttpException $e) {
        } // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        $brands = PropertyValue24::find()
            ->where(['b24property_id' => 107])
            ->all();
        $productsType = PropertyValue24::find()
            ->where(['b24property_id' => 108])
            ->all();

        return $this->render('index', [
            'page' => 'catalog',
            'action' => 'index',
            'brands' => $brands,
            'productsType' => $productsType
        ]);
    }

    private function findProducts(int $id): Products
    {
        if (($model = Products::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}
