<?php
namespace landing\controllers;

use landing\models\Product;
use models\Products;
use models\ProductsProperty;
use Yii;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use yii\web\NotFoundHttpException;

/**
 * Product controller
 */
class ProductController extends Controller
{
    private $lang = 'en';
    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function beforeAction($action)
    {
        $this->lang = 'ru';
        try {
            return parent::beforeAction($action);
        } catch (BadRequestHttpException $e) {
        } // TODO: Change the autogenerated stub
    }

    /**
     * Displays Product.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->goHome();
    }

    public function actionInfo($id = null)
    {
        $id = str_replace('.html' , '' , $id);
        if($prod = Product::find()
            ->select(['products.*' , 'ps.title_ru'])
            ->leftJoin('products_status ps' , 'ps.product_id=products.product_id')
            ->where(['ps.url' => $id])->one()){
                return $this->render('index', [
                    'product' => $prod,
                    'productProperty' => $prod->getProductProperty(),
                    'barcode' => $prod->getBarcode(),
                    'packages' => $prod->getPackages(),
                    'preview_img' => $prod->getLogo(),
                    'images' => $prod->getProductImages(),
                    ]);
        } else {
           return $this->goHome();
        }
    }

}