<?php

namespace models;


use Yii;
use yii\db\ActiveRecord;

/**
 * Products model
 *
 * @property integer $id
 */

class DealsProducts24 extends ActiveRecord
{
    public $pallet;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%b24_deals_products}}';
    }

    public function getValue($fieldid){
        if($prop = ProductsFieldsItem24::findOne(['product_id'=> $this->product_id , 'property_id'=>$fieldid ])){
            switch ($fieldid){
                case 104:
                    return  Company24::getCompanyName($prop->value);
            }
            return $prop->value;
        }
        return $fieldid;
    }

    public function getPriceBrutto(){
        return round($this->quantity * $this->price_brutto , 3);
    }

    public function getQuantity(){
        return $this->quantity . ' ' . $this->measure_name;
    }

    public function beforeSave($insert)
    {
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function loadFromArray($items){

        foreach ($items as $k => $item){
            $key = strtolower($k);
            $this->$key = $item;
        }
        return true;
    }

}