<?php

namespace models;

use bitrix\components\CRest;
use Yii;
use yii\db\ActiveRecord;

/**
 * Products model
 *
 * @property integer $id
 */

class DealsProductsFields24 extends ActiveRecord
{
    public $pallet;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%b24_deals_products_fields}}';
    }

    public function beforeSave($insert)
    {
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    static public function updateFields(){
        $deal = CRest::call('crm.productrow.fields');


        if ($deal && isset($deal['result']))
        {
            foreach ($deal['result'] as $k => $item){
                if(!$dpf = self::findOne(['name'=>$k])){
                    $dpf= new self();
                }
                $dpf->name = $k;
                $dpf->title = $item['title'];
                $dpf->type = $item['type'];
                $dpf->save();
            }
        }
    }

}