<?php

namespace models;

use bitrix\components\CRest;
use Yii;
use yii\db\ActiveRecord;

/**
 * Products model
 *
 * @property integer $id
 */
class HistoryCdn extends ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{history_cdn}}';
    }

    public function beforeSave($insert)
    {
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function getLickFolderCdn(int $idDeal, int $folderNumber)
    {
        if ($idDeal) {
            $links = [];
            $result = $this->get_cdn($idDeal);

            if ($folderNumber) {
                $folderArray = $folderNumber - 1;
                if (is_array($result) && key_exists('folders', $result)) {
                    foreach ($result['folders'][$folderArray]['files'] as $link) {
                        $links [] = $link['cdnUrl'];
                    }
                }
            }
            return $links;
        }
    }

    static public function getLickFolderCdnByUrl(int $idDeal, string $url)
    {
        if ($idDeal) {
            $links = [];
            $result = self::get_cdn($idDeal);
            if (is_array($result) && key_exists('folders', $result)) {
                foreach ($result['folders'] as $k => $folder) {
                    if ($folder['clientPanelUrl'] == $url) {
                        return $folder['files'];
                    }
                }
            }
            return $links;
        }
    }

    public function getIdFolderCdn(int $idDeal, string $url)
    {
        if ($idDeal) {
            $links = [];
            $result = $this->get_cdn($idDeal);
            if ($url) {
                if (is_array($result) && key_exists('folders', $result)) {
                    foreach ($result['folders'] as $k => $folder) {
                        if ($folder['clientPanelUrl'] == $url) {
                            return $folder['id'];
                        }
                    }
                }
            }
            return $links;
        }
    }

    public function getIdFileCdn (int $idDeal, string $urlFile)
    {
        if ($idDeal) {
            $links = [];
            $result = $this->get_cdn($idDeal);
            if ($urlFile) {
                if (is_array($result) && key_exists('folders', $result)) {
                    foreach ($result['folders'] as $k => $folder) {
                        foreach ($folder['files'] as $file )
                        if ($file['cdnUrl'] == $urlFile) {
                            return $file['id'];
                        }
                    }
                }
            }
            return $links;
        }
    }

    private function get_cdn($dealId)
    {
        $queryUrl = 'https://cdn.ttline.online/api/car/get-by-vin';
        $queryData = http_build_query(array(
            'vin' => $dealId,
        ));
        $curl = curl_init();
        curl_setopt_array($curl, array(
            CURLOPT_SSL_VERIFYPEER => 0,
            CURLOPT_POST => 1,
            CURLOPT_HEADER => 0,
            CURLOPT_RETURNTRANSFER => 1,
            CURLOPT_URL => $queryUrl,
            CURLOPT_POSTFIELDS => $queryData,
        ));
        $result = curl_exec($curl);
        curl_close($curl);

        return json_decode($result, true);
    }
}