<?php

namespace models;

use bitrix\components\CRest;
use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;
/**
 * Products model
 *
 * @property integer $id
 * @property string $tytle_ru
 */

class Measure24 extends ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%b24_measure}}';
    }

    public function beforeSave($insert)
    {
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    static function loadMeasureEntryFromB24(int $entryId)
    {

        $deal = CRest::call('crm.measure.list');


        if ($deal && isset($deal['result']))

            foreach ($deal['result'] as $k => $v){
                var_dump($v);

                if(!$vat = Measure24::findOne($v['ID'])){
                    $vat = new Measure24();
                }
                $vat->code = $v['CODE'];
                $vat->id = $v['ID'];
                $vat->title = $v['MEASURE_TITLE'];
                $vat->symbol = $v['SYMBOL_INTL'];
                $vat->save();

            }
    }
}