<?php

namespace models;

use bitrix\components\CRest;
use Yii;
use yii\db\ActiveRecord;

/**
 * Products model
 *
 * @property integer $id
 */

class ProductsFieldsItem24 extends ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%b24_product_fields_item}}';
    }

    public function beforeSave($insert)
    {
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public static function getValue($id , $fieldId)
    {
        if($prop = self::findOne(['id'=> $id , 'fields_id'=>$fieldId ])){
            switch ($id){
                case 104:
                    return  Company24::getCompanyName($prop->value);
            }
            return $prop->value;
        }
        return $id;
    }

}