<?php

namespace models;

use yii\db\ActiveRecord;

/**
 * Products model
 *
 * @property integer $id
 */

class ProductsProperty24 extends ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%b24_product_property}}';
    }

    public function beforeSave($insert)
    {
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    function getPallets($prodId){
        if($prodProp =  self::find()->where(['property_id'=>88, 'property_id'=> 89, 'product_id'=>$prodId])->all()){
            return $prodProp;
        }
        return 0;
    }

    public function getValueToArray($fieldid){
        if($prop = self::findOne(['product_id'=> $this->product_id , 'property_id'=>$fieldid ])){
            switch ($fieldid){
                case 104:
                    return  ['type' => 'select', 'id' => $prop->value , 'value' => Company24::getCompanyNamesByType('SUPPLIER')];
                default:
                    return ['type' => 'str' , 'value' => $prop->value];
                    break;
            }
        }
        return ['type' => 'str' , 'value' => $fieldid];
    }
}