<?php

namespace models;

use bitrix\components\CRest;
use Yii;
use yii\db\ActiveRecord;

/**
 * Products model
 *
 * @property integer $id
 */
class SpendingField extends ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%ttl_spending_fields}}';
    }

    public static function parceItem($item , $ln)
    {
        $t = 'title_' . $ln;
        $value = ['title' => $item->$t , 'name'=> $item->name , 'id'=>$item->field_id, 'value'=>''];
        switch ($item->type){
            case 'ttl_spen_type':
                $value['value']= SpendingType::find()->select(['type_id as id' , $t . ' as title'])->asArray()->all();
                $value['type'] = 'select';
                break;
            case 'ttl_vats':
                $value['value'] = Currency24::find()->select(['id' , 'title_ru as title'])->asArray()->all();
                $value['type'] = 'select';
                break;
            default:
                $value['type']= $item->type;
                break;

        }
        return $value;
    }

    public function beforeSave($insert)
    {
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}