<?php

namespace models;

use bitrix\components\CRest;
use Yii;
use yii\db\ActiveRecord;

/**
 * Products model
 *
 * @property integer $id
 */

class UsersFields24 extends ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%b24_users_fields}}';
    }

    public function beforeSave($insert)
    {
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    
    
    static public function updateUsersFieldsFromB24()
    {
        $fields24 = CRest::call('user.fields');

        if ($fields24 && isset($fields24['result'])) {

            foreach ($fields24['result'] as $k => $v) {
                if (!$field = self::findOne(['type' => $k])) {
                    $field = new self();
                }
                $field->type = $k;
                $field->title = $v;
                $field->save();
            }

            return true;
        }
        return null;
    }

    static public function getIdByType($type){
        if($val = self::findOne(['type'=>$type])){
            return $val->id;
        }
        return null;
    }
}